"""DB name&family_name&middle_name nullable=True

Revision ID: d48a994b234c
Revises: a1311c54602d
Create Date: 2024-03-16 20:02:54.866102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48a994b234c'
down_revision: Union[str, None] = 'a1311c54602d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Имя пользователя')
    op.alter_column('users', 'family_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Фамилия пользователя')
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Отчество пользователя')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Отчество пользователя')
    op.alter_column('users', 'family_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Фамилия пользователя')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Имя пользователя')
    # ### end Alembic commands ###
